# 2. Introducing Array in NumPy

In [2]:
#Calculate BMI
player_heights = [1.5, 1.7, 1.55, 1.68, 1.99, 1.87, 2.1, 1.45, 1.99, 1.83]
player_weights = [43, 77.3, 65.9, 33, 55, 57, 65.5, 69, 75, 65]

type(player_heights)
type(player_weights)

list

In [14]:
import numpy as np

player_heights_np = np.array(player_heights)
player_weights_np = np.array(player_weights)

bmi_np = player_weights_np/(player_heights_np**2)
bmi_np

array([19.11111111, 26.74740484, 27.42976067, 11.69217687, 13.88853817,
       16.30015156, 14.85260771, 32.81807372, 18.93891568, 19.4093583 ])

#### type() of numpy array 

In [6]:
#Find the type() of bmi_np
type(bmi_np)

#print(bmi_np)

numpy.ndarray

#### Feth the first element

In [7]:
bmi_np[0]

19.11111111111111

#### Fetch Last element

In [9]:
bmi_np[-1]

19.409358296754156

#### Fetch last 5

In [36]:
bmi_np[-5:]

array([16.30015156, 14.85260771, 32.81807372, 18.93891568, 19.4093583 ])

## Convert to 2D Array

In [40]:
# convert bmi_np to 2D array
bmi_np.reshape(5,2)

array([[19.11111111, 26.74740484],
       [27.42976067, 11.69217687],
       [13.88853817, 16.30015156],
       [14.85260771, 32.81807372],
       [18.93891568, 19.4093583 ]])