# 4. Creating NumPy Arrays

Understand the different ways in which Arrays can be created - 1D and 2D
1. `array()` - Create numpy array from List, tuples and dictionaries
2. `ones()` - Create an array of 1s.
3. `zeros()` - Create an array of 0s.
4. `arange()` - Create an array with the continuous integers.
5. `linspace()` - Generate values which are equally spaced from each other.
6. `random.random()` - Create array of random numbers

## 1. Create Array using `array()`

####  1.1. Create array from List

In [47]:
import numpy as np

player_heights = [1.5, 1.7, 1.55, 1.68, 1.99, 1.87, 2.1, 1.45, 1.99, 1.83]

# Create from a List
np_player_heights = np.array(player_heights)
np_player_heights

array([1.5 , 1.7 , 1.55, 1.68, 1.99, 1.87, 2.1 , 1.45, 1.99, 1.83])

In [4]:
# Create from a list
np_arr = np.array([111, 102, 145, 156])
np_arr

array([111, 102, 145, 156])

#### 1.2. Create array from Tuples

In [6]:
# Create from a Tuples
currencies = ("Dollars", "Rupees", "Pounds", "Euros")
currencies_arr = np.array(currencies)
currencies_arr

array(['Dollars', 'Rupees', 'Pounds', 'Euros'], dtype='<U7')

#### 1.3. Create array from Dictionaries - dict.items()

In [9]:
# Create from a Dictionary
currencies_dict = {"Dollars": "$", "Rupees": "₹", "Pounds": "£", "Euros": "€"}
print(currencies_dict.items())

currencies_2d_arr = np.array(list(currencies_dict.items()))
currencies_2d_arr

dict_items([('Dollars', '$'), ('Rupees', '₹'), ('Pounds', '£'), ('Euros', '€')])


array([['Dollars', '$'],
       ['Rupees', '₹'],
       ['Pounds', '£'],
       ['Euros', '€']], dtype='<U7')

In [10]:
currencies_2d_arr.dtype

dtype('<U7')

In [11]:
currencies_2d_arr.shape

(4, 2)

In [12]:
currencies_2d_arr.ndim

2

## 2. Create using `ones()`

In [14]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arr_ones = np.ones(10, dtype=int)
arr_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
arr_ones.ndim

1

In [20]:
arr_ones.size

10

In [21]:
arr_ones.shape

(10,)

#### 2.2. Introduction to reshape(m,n)

In [27]:
ones_2d_arr = arr_ones.reshape(2,5)
ones_2d_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
ones_2d_arr = arr_ones.reshape(2,6)
ones_2d_arr

ValueError: cannot reshape array of size 10 into shape (2,6)

In [29]:
ones_2d_arr.shape

(2, 5)

In [30]:
ones_2d_arr.size

10

In [31]:
type(ones_2d_arr)

numpy.ndarray

In [32]:
ones_2d_arr.itemsize

8

In [33]:
ones_2d_arr = arr_ones.reshape(2,5).astype('int32')
ones_2d_arr.itemsize

4

## 3. Create using `zeros()`

#### Simple 1xD Array with Zeros

In [36]:
zeros_arr = np.zeros(20)
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [38]:
zeros_arr.ndim

2

#### Simple, int type 2xD array with Zeros

In [39]:
zeros_arr = np.zeros(dtype=int, shape=(4,5))
zeros_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
zeros_arr.ndim

2

## 4. Create array using `arange()`
#### 4.1. Simple 1xD Array

In [41]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

#### 4.2. Simple 2xD Array

In [44]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## 5. Create array using `linspace()`
Array of length 30 between 1 and 500

In [48]:
np.linspace(1,500,30)

array([  1.        ,  18.20689655,  35.4137931 ,  52.62068966,
        69.82758621,  87.03448276, 104.24137931, 121.44827586,
       138.65517241, 155.86206897, 173.06896552, 190.27586207,
       207.48275862, 224.68965517, 241.89655172, 259.10344828,
       276.31034483, 293.51724138, 310.72413793, 327.93103448,
       345.13793103, 362.34482759, 379.55172414, 396.75862069,
       413.96551724, 431.17241379, 448.37931034, 465.5862069 ,
       482.79310345, 500.        ])

In [49]:
np.linspace(1,500,30).reshape(5,6)

array([[  1.        ,  18.20689655,  35.4137931 ,  52.62068966,
         69.82758621,  87.03448276],
       [104.24137931, 121.44827586, 138.65517241, 155.86206897,
        173.06896552, 190.27586207],
       [207.48275862, 224.68965517, 241.89655172, 259.10344828,
        276.31034483, 293.51724138],
       [310.72413793, 327.93103448, 345.13793103, 362.34482759,
        379.55172414, 396.75862069],
       [413.96551724, 431.17241379, 448.37931034, 465.5862069 ,
        482.79310345, 500.        ]])

## 6. Create array of random numbers - `np.random.random()`
Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.

#### 5.1. Generate a random number

In [87]:
np.random.random()

0.7005641751122824

#### 5.2. Generate an [m, n] array filled with random floats

In [88]:
np.random.random([5,4])

array([[0.4422161 , 0.25502898, 0.95435992, 0.35868228],
       [0.78998432, 0.0239979 , 0.8641468 , 0.77998807],
       [0.90091783, 0.67729624, 0.13667759, 0.40964513],
       [0.39966322, 0.31879619, 0.54035549, 0.34147156],
       [0.91265477, 0.12866876, 0.99119529, 0.07013218]])

#### 5.3. [m, n] array filled with random floats between 0 to 100

In [90]:
np.random.random([5,4])*100

array([[52.63469094, 89.57336195, 93.2570331 , 57.95421345],
       [86.27221913, 87.29223067, 36.35630319, 87.80296347],
       [88.69956116,  0.97124162, 59.92526714, 47.93593397],
       [51.95345875, 44.85057716, 88.03132234, 43.54499961],
       [61.11541602, 28.32439685, 28.75485198,  3.45255401]])

#### 5.3. Generate an [m, n] array filled with random integers - 0 to 12

In [93]:
np_int32_rarray = (np.random.random([4,5])*12).astype('int32')
np_int32_rarray

array([[ 0,  6,  5,  1,  7],
       [ 7,  1,  0, 10,  1],
       [ 9,  3,  9,  7, 11],
       [ 3,  9,  8,  1,  9]], dtype=int32)