# 6. Broadcasting in NumPy

- **Boradcasting** is about how NumPy treats arrays with different shapes to perform arithmetic opearations.
- The **smaller array** is broadcasted over the larger array to make them compatible.

Discussing several examples below to understand this well.

In [1]:
import numpy as np

### 1. Arithmetic operations on Array[m, n] with Array[1, 1] - Element repetition

In [2]:
Arr_1 = np.arange(9).reshape(3,3).astype('int32')
Arr_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [4]:
Arr_2 = np.array([1])
Arr_2

array([1])

In [5]:
# Add them
Arr_1 + Arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Multiply them
Arr_1 * Arr_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. Arithmetic operations on Array[m, n] with Array[n, 1] - Column repetitions

In [10]:
Arr_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [11]:
Arr_3 = np.array([1,2,3]).reshape(3,1)
Arr_3

array([[1],
       [2],
       [3]])

In [12]:
Arr_1*Arr_3

array([[ 0,  1,  2],
       [ 6,  8, 10],
       [18, 21, 24]])

### 3. Arithmetic operations on Array[m, n] with Array[1, n] - row repetitions 

In [13]:
Arr_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)

In [14]:
Arr_4 = np.arange(1,4).reshape(1,3)
Arr_4

array([[1, 2, 3]])

In [15]:
Arr_1*Arr_4

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [16]:
Arr_1 + Arr_4

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [17]:
Arr_1 - Arr_4

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

### 4. Arithmetic operations on Array[m, 1] with Array [1, m]


In [18]:
Arr_mn = np.arange(1,5).astype(int).reshape(4,1)
Arr_mn

array([[1],
       [2],
       [3],
       [4]])

In [19]:
Arr_nm = np.arange(1,5).astype(int).reshape(1,4)
Arr_nm

array([[1, 2, 3, 4]])

In [20]:
Arr_mn * Arr_nm

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

### 5. Arithmetic operations on Array[m, n] with Array [l, m] ------???
Try this out and check the output yourself.


In [21]:
Arr_mn = np.arange(10).astype(int).reshape(5,2)
Arr_mn

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
Arr_lm = np.arange(10, 20).astype(int).reshape(2,5)
Arr_lm

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
Arr_mn * Arr_lm

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 