# 1. Getting started with NumPy

In [1]:
#Sides of Square
square_sides = [4, 5, 6, 7, 9, 89, 99]
type(square_sides)

list

In [2]:
#Calculate the Area - side*side
square_areas = [a*a for a in square_sides]
square_areas

[16, 25, 36, 49, 81, 7921, 9801]

In [3]:
#Can I directly calculate the square
square_areas = square_sides*square_sides

TypeError: can't multiply sequence by non-int of type 'list'

# Introducing NumPy

In [4]:
import numpy as np

sides_array = np.array(square_sides)

area_array = sides_array*sides_array
print(area_array)

[  16   25   36   49   81 7921 9801]


### Array addition example

In [5]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,4,3,2,1])

array1+array2

array([6, 6, 6, 6, 6])

## Calculate the BMI

In [6]:
heights_in_mtr = np.array([1.72, 1.75, 1.72, 1.45, 1.50, 2.10])
weights_in_kg = np.array([65, 75, 99, 33, 45, 95])

#Calculate BMI - Kg/mtr**2
bmi_array = weights_in_kg/(heights_in_mtr**2)
bmi_array

array([21.97133586, 24.48979592, 33.46403461, 15.69560048, 20.        ,
       21.54195011])

## Quizz - What will be the result

In [7]:
quizz1 = np.array( [2, 2.5, False, 0.2, 333, True, "name"] )
print(quizz1)

['2' '2.5' 'False' '0.2' '333' 'True' 'name']


In [8]:
quizz2 = np.array( [2, 2.5, False, 0.2, 333, True] ).astype('int')
quizz2

array([  2,   2,   0,   0, 333,   1])

In [ ]:
#Is it possible to create an array from a tuples and Dictionaries?
