# 5. Indexing in NumPy - Array
- First element
- Last element
- Get a row from a [m, n] array - Grid
- Get a column from a [m, n] array - Grid
- Get a small matrix - [a, b] from an array [m, n]
- Obtain a specific indices from an [m, n] array

Indexing means accessing a particular value in an Array. In this case it is NumPy array. Each item in the NumPy Array stored at a specific index.

In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 1. Accessing the first element


In [3]:
A[0,0]

0

### 2. Accessign the last element

In [4]:
A[-1,-1]

11

### 3. Accessing the row 

In [5]:
A[1]

array([3, 4, 5])

In [8]:
A[1,:]

array([3, 4, 5])

### 4. Access a column

In [10]:
A[:,-1]

array([ 2,  5,  8, 11])

In [12]:
A[:,2]

array([ 2,  5,  8, 11])

### 5. Get a sub-array from an Array

In [13]:
B = A[1:,1:]
B

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

#### rehsape the array - B

In [14]:
B.reshape(2,3)

array([[ 4,  5,  7],
       [ 8, 10, 11]])

### 6. Create an array with the specific indices from an [m, n] array

In [16]:
#Extract only [0, 5] - https://stackoverflow.com/questions/65510193/get-specific-indices-from-a-grid-in-numpy
C = A[[0,1], [0,2]] #[row1,row2,row3], [column1, column2, column3]
C

array([0, 5])

In [17]:
## Incomplete code - uncomment and try
C = A[[0,1,3], [0,2,2]]
C

array([ 0,  5, 11])